version: '3.5'

services:
  laravel:
    build:
      context: '.'
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80

  pgsql:
    image: postgres:9.5
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret

  phppgadmin:
    image: neimheadh/phppgadmin:latest
    ports:
      - '8888:80'
    environment:
      - POSTGRES_HOST=pgsql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=laravel
      - POSTGRES_PASS=secret
    depends_on:
      - pgsql

#  redis:
#    build:
#        context: ./redis
#    volumes:
#        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#        - ./docker/redis:/data
#    ports:
#        - '6379:6379'

#  supervisor:
#    build:
#        context: ./docker/supervisor
#    volumes:
#        - .:/var/www/html
